ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - workerd

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@fabdeh/eslint-config'
