minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@fabdeh/*'

onlyBuiltDependencies:
  - '@fabdeh/eslint-config'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver
