// spartan/ui Helm code, generated by `@spartan-ng/cli:ui`. It keeps spartan's own conventions so that
// regenerating components and running `@spartan-ng/cli:healthcheck` stay painless, so it is linted with
// the Nx Angular presets rather than the workspace's `@fabdeh/eslint-config` style rules.
import nx from '@nx/eslint-plugin';

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/angular'],
  ...nx.configs['flat/angular-template'],
  {
    files: ['**/*.ts'],
    rules: {
      '@angular-eslint/directive-selector': ['error', { type: 'attribute', prefix: 'hlm', style: 'camelCase' }],
      '@angular-eslint/component-selector': ['error', { type: 'element', prefix: 'hlm', style: 'kebab-case' }],
      '@angular-eslint/no-input-rename': 'off',
      '@angular-eslint/directive-class-suffix': 'off',
      '@angular-eslint/component-class-suffix': 'off',
      '@nx/enforce-module-boundaries': ['error', { allowCircularSelfDependency: true }],
    },
  },
];
